"""
Django settings for carpi_news project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-j*z9sjtd7=#390n_z8bmi9)ca2u%b=p2=z8!ira%7!9ry(wd=u')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ['true', '1', 'yes']

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',  # Rich text editor
    'home.apps.HomeConfig',  # Usa la configurazione personalizzata
    'admin_panel.apps.AdminPanelConfig',  # Admin panel per banner e gestione
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'home.middleware.SEOMiddleware',  # Redirect HTTP→HTTPS e www→non-www
    'home.middleware.SecurityHeadersMiddleware',  # CSP e security headers
    'home.middleware.cache_headers.StaticMediaCacheMiddleware',  # Cache headers per static/media
    'django.middleware.gzip.GZipMiddleware',  # Compressione GZIP per performance
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'carpi_news.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.canonical_url',  # URL canonici
                'home.context_processors.categorie_menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'carpi_news.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use DATABASE_URL if available (for production with PostgreSQL/MySQL)
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Production database (PostgreSQL/MySQL)
    import dj_database_url
    DATABASES = {
        'default': {
            **dj_database_url.parse(DATABASE_URL),
            'CONN_MAX_AGE': 0,  # Chiudi connessione dopo ogni request (evita accumulo con thread monitor)
        }
    }
else:
    # Development database (SQLite) con ottimizzazioni aggressive per produzione
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 60,  # Timeout aumentato a 60 sec per 22 monitor concorrenti
                'init_command': (
                    'PRAGMA journal_mode=WAL;'       # Write-Ahead Logging: migliora concorrenza
                    'PRAGMA synchronous=NORMAL;'     # Bilanciamento velocità/sicurezza
                    'PRAGMA cache_size=-128000;'     # 128MB cache (era 64MB)
                    'PRAGMA temp_store=MEMORY;'      # Tabelle temporanee in RAM
                    'PRAGMA mmap_size=536870912;'    # 512MB memory-mapped I/O (era 256MB)
                    'PRAGMA busy_timeout=30000;'     # 30 sec busy timeout
                    'PRAGMA wal_autocheckpoint=1000;'# Checkpoint ogni 1000 pagine
                )
            },
            # Connection pooling (riusa connessioni)
            'CONN_MAX_AGE': 600,  # Riusa connessioni per 10 minuti
        }
    }


CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'IGNORE_EXCEPTIONS': True,  # se Redis è down, fallback silenzioso
        },
        'TIMEOUT': 300,  # 5 minuti — stesso TTL della cache homepage
        'KEY_PREFIX': 'odp',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'it-IT'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Date and time formats
DATE_FORMAT = 'd F Y'
DATETIME_FORMAT = 'd F Y H:i'
SHORT_DATE_FORMAT = 'd/m/Y'

# Month names in Italian
MONTH_NAMES = [
    None, 'gennaio', 'febbraio', 'marzo', 'aprile', 'maggio', 'giugno',
    'luglio', 'agosto', 'settembre', 'ottobre', 'novembre', 'dicembre'
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.getenv('STATIC_URL', '/static/')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'home', 'static'),
    os.path.join(BASE_DIR, 'admin_panel', 'static'),
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'carpi_news.log',
            'maxBytes': 1024*1024*10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'playlist_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'playlist_monitor.log',
            'maxBytes': 1024*1024*5,  # 5MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
        'instagram_webhook_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'instagram_webhook.log',
            'maxBytes': 1024*1024*5,
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'home.views': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'home.signals': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'home.playlist_monitor': {
            'handlers': ['console', 'playlist_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'home.instagram_webhook': {
            'handlers': ['console', 'instagram_webhook_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'root': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
}

# YouTube Playlist Monitor Configuration
YOUTUBE_PLAYLIST_MONITOR = {
    'ENABLED': os.getenv('YOUTUBE_MONITOR_ENABLED', 'True').lower() in ['true', '1', 'yes'],
    'PLAYLIST_ID': os.getenv('YOUTUBE_PLAYLIST_ID', ''),
    'API_KEY': os.getenv('YOUTUBE_API_KEY', ''),
    'CHECK_INTERVAL': int(os.getenv('YOUTUBE_CHECK_INTERVAL', '300')),  # seconds
}

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ['true', '1', 'yes']
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ['true', '1', 'yes']
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = f'Ombra del Portico <{os.getenv("EMAIL_HOST_USER", "noreply@ombradelportico.it")}>'

# Admin notification settings
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', EMAIL_HOST_USER)


# Universal Monitor System Configuration
UNIVERSAL_MONITORS = {
    'ENABLED': os.getenv('UNIVERSAL_MONITORS_ENABLED', 'True').lower() in ['true', '1', 'yes'],
    'MONITORS': [
        ('carpi_calcio', int(os.getenv('MONITOR_INTERVAL_CARPI_CALCIO', '900'))),
        ('comune_carpi', int(os.getenv('MONITOR_INTERVAL_COMUNE_CARPI', '1800'))),
        ('youtube', int(os.getenv('MONITOR_INTERVAL_YOUTUBE', '600'))),
        ('ansa', int(os.getenv('MONITOR_INTERVAL_ANSA', '3600'))),
        ('eventi_carpi', int(os.getenv('MONITOR_INTERVAL_EVENTI_CARPI', '1800'))),
        ('voce_carpi', int(os.getenv('MONITOR_INTERVAL_VOCE_CARPI', '2400'))),
        ('tempo_carpi', int(os.getenv('MONITOR_INTERVAL_TEMPO_CARPI', '2400'))),
        ('generic_html', int(os.getenv('MONITOR_INTERVAL_GENERIC_HTML', '3600'))),
    ]
}

# CSRF Settings
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if os.getenv('CSRF_TRUSTED_ORIGINS') else []
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'

# Security Settings for Production
if not DEBUG:
    # HTTPS Redirect e Proxy SSL Header (necessario per Apache reverse proxy)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() in ['true', '1', 'yes']

    # HSTS (HTTP Strict Transport Security) - 1 anno
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Altre impostazioni di sicurezza
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True').lower() in ['true', '1', 'yes']
    CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True').lower() in ['true', '1', 'yes']
    X_FRAME_OPTIONS = 'DENY'

# AI API Configuration
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# PayPal Payment Configuration
PAYPAL_MODE = os.getenv('PAYPAL_MODE', 'sandbox')  # sandbox or live
PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID', '')
PAYPAL_CLIENT_SECRET = os.getenv('PAYPAL_CLIENT_SECRET', '')

# Site URL for media files
SITE_URL = os.getenv('SITE_URL', 'https://ombradelportico.it')
FACEBOOK_PAGE_URL = os.getenv('FACEBOOK_PAGE_URL', 'https://www.facebook.com/ombradelportico')
TWITTER_SITE = os.getenv('TWITTER_SITE', '@ombradelportico')

# YouTube API Configuration
YOUTUBE_API_KEY = os.getenv('YOUTUBE_API_KEY', '')
YOUTUBE_PLAYLIST_ID = os.getenv('YOUTUBE_PLAYLIST_ID', '')

# Social Media Auto-Sharing Configuration
# Facebook e Twitter ora gestiti automaticamente via RSS + IFTTT
# Vedi feed RSS disponibili:
# - https://ombradelportico.it/feed/rss/
# - https://ombradelportico.it/feed/recenti/ (ottimizzato per IFTTT)
# - https://ombradelportico.it/feed/atom/

# Telegram (condivisione diretta tramite Bot API)
TELEGRAM_AUTO_SHARE = os.getenv('TELEGRAM_AUTO_SHARE', 'False').lower() in ['true', '1', 'yes']
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID', '')

# Facebook (condivisione diretta tramite Graph API)
FACEBOOK_AUTO_SHARE = os.getenv('FACEBOOK_AUTO_SHARE', 'False').lower() in ['true', '1', 'yes']
FACEBOOK_PAGE_ID = os.getenv('FACEBOOK_PAGE_ID', '')
FACEBOOK_ACCESS_TOKEN = os.getenv('FACEBOOK_ACCESS_TOKEN', '')
FACEBOOK_APP_ID = os.getenv('FACEBOOK_APP_ID', '')
FACEBOOK_APP_SECRET = os.getenv('FACEBOOK_APP_SECRET', '')

# Facebook Story/Reel auto-publishing
# Quando True, alla pubblicazione del post Pagina viene generato e pubblicato
# anche un video verticale 1080x1920 con foto+titolo+CTA+musica royalty-free
# come Storia e/o vero Reel Facebook via /video_reels.
FACEBOOK_REEL_ENABLED = os.getenv('FACEBOOK_REEL_ENABLED', 'False').lower() in ['true', '1', 'yes']
FACEBOOK_STORY_ENABLED = os.getenv('FACEBOOK_STORY_ENABLED', 'False').lower() in ['true', '1', 'yes']
FACEBOOK_REEL_DURATION = int(os.getenv('FACEBOOK_REEL_DURATION', '15'))
FACEBOOK_REEL_FPS = int(os.getenv('FACEBOOK_REEL_FPS', '24'))
# Cartella con tracce royalty-free (MP3/WAV/M4A). Vuoto = pad ambient procedurale di fallback.
FACEBOOK_REEL_MUSIC_DIR = os.getenv('FACEBOOK_REEL_MUSIC_DIR', '')

# Instagram (condivisione diretta tramite Instagram Graph API)
# Richiede account Instagram Business/Creator collegato alla pagina Facebook
INSTAGRAM_AUTO_SHARE = os.getenv('INSTAGRAM_AUTO_SHARE', 'False').lower() in ['true', '1', 'yes']
INSTAGRAM_ACCOUNT_ID = os.getenv('INSTAGRAM_ACCOUNT_ID', '')

# Instagram Story / Reel auto-publishing (oltre al post in feed)
# Stesso video verticale 1080x1920 con musica del Reel Facebook,
# pubblicato come Storia (sparisce in 24h) e/o Reel (permanente).
INSTAGRAM_STORY_ENABLED = os.getenv('INSTAGRAM_STORY_ENABLED', 'False').lower() in ['true', '1', 'yes']
INSTAGRAM_REEL_ENABLED = os.getenv('INSTAGRAM_REEL_ENABLED', 'False').lower() in ['true', '1', 'yes']
INSTAGRAM_WEBHOOK_VERIFY_TOKEN = os.getenv('INSTAGRAM_WEBHOOK_VERIFY_TOKEN', '')
INSTAGRAM_APP_SECRET = os.getenv('INSTAGRAM_APP_SECRET', '')
INSTAGRAM_PAGE_ACCESS_TOKEN = os.getenv('INSTAGRAM_PAGE_ACCESS_TOKEN', FACEBOOK_ACCESS_TOKEN)
INSTAGRAM_AUTO_DM_ACCEPT_ANY_EMOJI = os.getenv('INSTAGRAM_AUTO_DM_ACCEPT_ANY_EMOJI', 'True').lower() in ['true', '1', 'yes']
INSTAGRAM_AUTO_DM_TEXT_TRIGGERS = [
    item.strip().upper()
    for item in os.getenv('INSTAGRAM_AUTO_DM_TEXT_TRIGGERS', 'LINK,INFO,LEGGI').split(',')
    if item.strip()
]
INSTAGRAM_AUTO_DM_STORY_FALLBACK_MINUTES = int(os.getenv('INSTAGRAM_AUTO_DM_STORY_FALLBACK_MINUTES', '1440'))
INSTAGRAM_AUTO_DM_REEL_FALLBACK_MINUTES = int(os.getenv('INSTAGRAM_AUTO_DM_REEL_FALLBACK_MINUTES', '4320'))
INSTAGRAM_WEBHOOK_HANDLE_SYNC = os.getenv('INSTAGRAM_WEBHOOK_HANDLE_SYNC', 'False').lower() in ['true', '1', 'yes']

# Metadati avanzati Reel/Storia per migliorare discovery
# CARPI_PLACE_ID: Facebook Place ID di Carpi. Usato come location tag su FB Reel
# e IG Reel/Story. Per trovarlo: https://developers.facebook.com/tools/explorer/
# query "pages/search?q=Carpi&type=place". Senza, il tag non viene applicato.
CARPI_PLACE_ID = os.getenv('CARPI_PLACE_ID', '')
# Audio name brandizzato sul Reel IG ('Audio originale di <nome>' visto dagli utenti)
INSTAGRAM_REEL_AUDIO_NAME = os.getenv('INSTAGRAM_REEL_AUDIO_NAME', 'Ombra del Portico - Notizie di Carpi')

# CKEditor Configuration
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_Full': [
            ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates'],
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'],
            ['Find', 'Replace', '-', 'SelectAll'],
            ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField'],
            '/',
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe'],
            '/',
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'ShowBlocks'],
        ],
        'toolbar': 'Full',
        'height': 500,
        'width': '100%',
        'filebrowserWindowWidth': 940,
        'filebrowserWindowHeight': 725,
        # CSS personalizzato per area Source (testo nero su sfondo bianco)
        'contentsCss': [],
        'bodyClass': 'ckeditor-body',
        'extraAllowedContent': '*(*);*{*}',  # Permetti tutti gli stili e classi
    }
}

# CSS personalizzato per CKEditor Source mode
CKEDITOR_CONFIGS['default']['contentsCss'] = []
