# Railway Deployment Configuration
[build]
  builder = "nixpacks"

[deploy]
  startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn carpi_news.wsgi:application"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[environment]
  DEBUG = "False"
  PYTHONUNBUFFERED = "1"