# Generated by Django 5.2.5 on 2025-08-31 06:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='categoria',
            field=models.CharField(default='Generale', max_length=100),
        ),
        migrations.AddField(
            model_name='articolo',
            name='data_pubblicazione',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articolo',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='articolo',
            name='sommario',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='titolo',
            field=models.CharField(max_length=200),
        ),
    ]
