# Generated by Django 5.2.5 on 2025-08-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_articolo_categoria_articolo_data_pubblicazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='data_pubblicazione',
            field=models.DateTimeField(),
        ),
    ]
