# Generated by Django 5.2.5 on 2025-08-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_articolo_data_pubblicazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='approvato',
            field=models.BooleanField(default=False),
        ),
    ]
