# Generated by Django 5.2.5 on 2025-08-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_articolo_approvato'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='fonte',
            field=models.URLField(blank=True, null=True),
        ),
    ]
