# Generated by Django 5.2.5 on 2025-08-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_articolo_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
