# Generated by Django 5.2.5 on 2025-09-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_articolo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='data_pubblicazione',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
