# Generated by Django 5.2.5 on 2025-09-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_articolo_data_pubblicazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='data_creazione',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='data_pubblicazione',
            field=models.DateTimeField(),
        ),
    ]
