# Generated by Django 5.2.5 on 2025-09-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_articolo_data_creazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='data_pubblicazione',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
