# Generated by Django 5.2.5 on 2025-09-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_articolo_data_creazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='data_pubblicazione',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
