# Generated by Django 5.2.5 on 2025-09-01 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_articolo_data_pubblicazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='data_pubblicazione',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
