# Generated by Django 5.2.5 on 2025-09-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_articolo_data_pubblicazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='richieste_modifica',
            field=models.TextField(blank=True, help_text="Richieste specifiche per la rigenerazione AI dell'articolo", null=True),
        ),
    ]
