# Generated by Django 5.2.5 on 2025-09-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_articolo_richieste_modifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text="Numero di visualizzazioni dell'articolo"),
        ),
    ]
