# Generated by Django 5.2.5 on 2025-09-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_articolo_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='foto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
