# Generated by Django 5.2.5 on 2025-09-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_articolo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='foto_upload',
            field=models.ImageField(blank=True, help_text="Upload di un'immagine per l'articolo", null=True, upload_to='images/uploaded/'),
        ),
    ]
