# Generated by Django 5.2.5 on 2025-09-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_articolo_foto_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='fonti_web',
            field=models.JSONField(blank=True, help_text='Fonti web utilizzate durante la generazione AI con ricerca web', null=True),
        ),
    ]
