# Generated by Django 5.2.5 on 2025-09-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_add_fonti_web_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='fonte',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
