# Generated by Django 5.2.5 on 2025-09-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_add_fonti_web_field'),
        ('home', '0016_articolo_fonti_web'),
    ]

    operations = [
    ]
