# Generated by Django 5.2.5 on 2025-10-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_articolo_fonte'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome identificativo del monitor', max_length=200, unique=True)),
                ('base_url', models.URLField(help_text='URL base del sito', max_length=500)),
                ('scraper_type', models.CharField(choices=[('html', 'HTML Scraping'), ('wordpress_api', 'WordPress API'), ('youtube_api', 'YouTube API'), ('graphql', 'GraphQL API'), ('email', 'Email IMAP')], help_text='Tipo di scraper da utilizzare', max_length=20)),
                ('category', models.CharField(default='Generale', help_text='Categoria degli articoli', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Monitor attivo/disattivo')),
                ('auto_approve', models.BooleanField(default=False, help_text='Approva automaticamente gli articoli')),
                ('config_data', models.JSONField(blank=True, default=dict, help_text='Configurazioni specifiche del monitor (selectors, API keys, etc.)')),
                ('use_ai_generation', models.BooleanField(default=False, help_text='Usa generazione AI')),
                ('enable_web_search', models.BooleanField(default=False, help_text='Abilita ricerca web durante generazione AI')),
                ('ai_system_prompt', models.TextField(blank=True, help_text="System prompt per l'AI")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, help_text='Ultima esecuzione del monitor', null=True)),
            ],
            options={
                'verbose_name': 'Configurazione Monitor',
                'verbose_name_plural': 'Configurazioni Monitor',
                'ordering': ['name'],
            },
        ),
    ]
