# Generated by Django 5.2.5 on 2025-10-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_monitorconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorconfig',
            name='base_url',
            field=models.URLField(blank=True, help_text='URL base del sito (opzionale per email)', max_length=500),
        ),
    ]
