# Generated by Django 5.2.5 on 2025-10-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_merge_20250930_1327'),
        ('home', '0019_alter_monitorconfig_base_url'),
    ]

    operations = [
    ]
