# Generated by Django 5.2.7 on 2025-10-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_monitorconfig_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='internal_links',
            field=models.JSONField(blank=True, default=list, help_text="Link interni suggeriti dall'AI per SEO", null=True),
        ),
    ]
