# Generated by Django 5.2.5 on 2025-10-24 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_articolo_internal_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='internal_links',
        ),
    ]
