# Generated by Django 5.2.5 on 2025-10-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_merge_20251008_1206'),
        ('home', '0021_remove_internal_links_field'),
    ]

    operations = [
    ]
