# Generated by Django 5.2.7 on 2025-10-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_internal_links_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='data_evento',
            field=models.DateField(blank=True, help_text="Data dell'evento per articoli di categoria Cultura ed Eventi", null=True),
        ),
    ]
