# Generated by Django 5.2.5 on 2025-10-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_add_data_evento_field'),
        ('home', '0022_merge_20251025_0107'),
    ]

    operations = [
    ]
