# Generated by Django 5.2.7 on 2025-11-02 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_add_data_evento_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('anthropic', 'Anthropic Claude'), ('google_search', 'Google Search')], help_text='Tipo di API utilizzata', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data e ora della chiamata')),
                ('operation', models.CharField(help_text="Operazione eseguita (es. 'generate_article', 'polish_content')", max_length=100)),
                ('model', models.CharField(blank=True, help_text="Modello utilizzato (es. 'claude-3-5-sonnet-20241022')", max_length=100)),
                ('input_tokens', models.IntegerField(default=0, help_text='Token di input (prompt)')),
                ('output_tokens', models.IntegerField(default=0, help_text='Token di output (risposta)')),
                ('search_queries', models.IntegerField(default=0, help_text='Numero di query di ricerca')),
                ('input_cost', models.DecimalField(decimal_places=6, default=0, help_text='Costo input in USD', max_digits=10)),
                ('output_cost', models.DecimalField(decimal_places=6, default=0, help_text='Costo output in USD', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, help_text='Costo totale in USD', max_digits=10)),
                ('success', models.BooleanField(default=True, help_text='Chiamata riuscita')),
                ('error_message', models.TextField(blank=True, help_text='Messaggio di errore se fallita')),
                ('related_article', models.ForeignKey(blank=True, help_text='Articolo correlato', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.articolo')),
            ],
            options={
                'verbose_name': 'Utilizzo API',
                'verbose_name_plural': 'Utilizzo API',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'api_type'], name='home_apiusa_timesta_36953d_idx'), models.Index(fields=['api_type', '-timestamp'], name='home_apiusa_api_typ_bfda14_idx')],
            },
        ),
    ]
