# Generated by Django 5.2.7 on 2025-11-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_apiusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiusage',
            name='input_cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Costo input in EUR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='apiusage',
            name='output_cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Costo output in EUR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='apiusage',
            name='total_cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Costo totale in EUR', max_digits=10),
        ),
    ]
