# Generated by Django 5.2.5 on 2025-11-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_merge_20251025_1105'),
        ('home', '0024_update_apiusage_help_text'),
    ]

    operations = [
    ]
