# Generated by Django 5.2.5 on 2025-11-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_update_apiusage_help_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiusage',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='apiusage',
            name='cost_total',
            field=models.DecimalField(db_column='total_cost', decimal_places=6, default=0, help_text='Costo totale in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='apiusage',
            name='input_cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Costo input in USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='apiusage',
            name='output_cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Costo output in USD', max_digits=10),
        ),
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='ID univoco della sessione chat', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data e ora del messaggio')),
                ('user_message', models.TextField(help_text="Messaggio dell'utente")),
                ('bot_response', models.TextField(help_text='Risposta del bot')),
                ('intent_data', models.JSONField(default=dict, help_text='Dati intent estratti (keywords, timeframe, ecc.)')),
                ('articles_found', models.IntegerField(default=0, help_text='Numero di articoli trovati')),
                ('articles_ids', models.JSONField(default=list, help_text='IDs degli articoli restituiti')),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text="IP dell'utente", null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent del browser')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Tempo di risposta in millisecondi', null=True)),
            ],
            options={
                'verbose_name': 'Conversazione Chatbot',
                'verbose_name_plural': 'Conversazioni Chatbot',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='home_chatbo_timesta_e72424_idx'), models.Index(fields=['session_id', '-timestamp'], name='home_chatbo_session_5a8501_idx')],
            },
        ),
    ]
