# Generated by Django 5.2.5 on 2025-11-10 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_apiusage_total_cost_apiusage_cost_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticoloPubbliredazionale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_azienda', models.CharField(help_text="Nome dell'azienda per cui creare il pubbliredazionale", max_length=200, verbose_name='Nome azienda')),
                ('sito_web', models.URLField(help_text="URL del sito web dell'azienda", max_length=500, verbose_name='Sito web')),
                ('categoria', models.CharField(default='Attualità', help_text="Categoria dell'articolo", max_length=100, verbose_name='Categoria')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('interview_in_progress', 'Intervista in corso'), ('interview_completed', 'Intervista completata'), ('pending_payment', 'In attesa di pagamento'), ('pending_approval', 'In attesa di approvazione'), ('approved', 'Approvato'), ('published', 'Pubblicato'), ('rejected', 'Rifiutato')], default='draft', max_length=30, verbose_name='Stato')),
                ('interview_data', models.JSONField(blank=True, default=dict, help_text='Conversazione AI e informazioni raccolte', verbose_name='Dati intervista')),
                ('titolo', models.CharField(blank=True, max_length=200, verbose_name='Titolo')),
                ('contenuto', models.TextField(blank=True, verbose_name='Contenuto')),
                ('sommario', models.TextField(blank=True, max_length=5000, verbose_name='Sommario')),
                ('foto', models.URLField(blank=True, max_length=500, null=True, verbose_name='Foto URL')),
                ('total_price', models.DecimalField(decimal_places=2, default=5.0, editable=False, max_digits=10, verbose_name='Prezzo totale (€)')),
                ('payment_status', models.CharField(choices=[('pending', 'In attesa'), ('completed', 'Completato'), ('failed', 'Fallito'), ('refunded', 'Rimborsato')], default='pending', max_length=20, verbose_name='Stato pagamento')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Metodo di pagamento')),
                ('payment_transaction_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID transazione')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data pagamento')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approvato il')),
                ('admin_notes', models.TextField(blank=True, help_text='Visibili solo agli admin', verbose_name='Note amministrative')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Pubblicato il')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pubbliredazionali_approvati', to=settings.AUTH_USER_MODEL, verbose_name='Approvato da')),
                ('articolo_pubblicato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pubbliredazionale_source', to='home.articolo', verbose_name='Articolo pubblicato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubbliredazionali', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Articolo Pubbliredazionale',
                'verbose_name_plural': 'Articoli Pubbliredazionali',
                'ordering': ['-created_at'],
            },
        ),
    ]
