# Generated by Django 5.2.5 on 2025-11-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_merge_20251103_0959'),
        ('home', '0025_remove_apiusage_total_cost_apiusage_cost_total_and_more'),
    ]

    operations = [
    ]
