# Generated by Django 5.2.7 on 2025-11-13 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_pubbliredazionali(apps, schema_editor):
    """Migra dati da ArticoloPubbliredazionale ad Articolo"""
    from django.utils.text import slugify

    ArticoloPubbliredazionale = apps.get_model('home', 'ArticoloPubbliredazionale')
    Articolo = apps.get_model('home', 'Articolo')

    for pub in ArticoloPubbliredazionale.objects.all():
        # Se esiste già un articolo pubblicato collegato, aggiorna quello
        if pub.articolo_pubblicato:
            articolo = pub.articolo_pubblicato
            articolo.is_pubbliredazionale = True
            articolo.pubbliredazionale_user = pub.user
            articolo.nome_azienda = pub.nome_azienda
            articolo.sito_web = pub.sito_web
            articolo.pubbliredazionale_status = pub.status
            articolo.interview_data = pub.interview_data
            articolo.payment_status = pub.payment_status
            articolo.payment_method = pub.payment_method or ''
            articolo.payment_transaction_id = pub.payment_transaction_id or ''
            articolo.payment_date = pub.payment_date
            articolo.total_price = pub.total_price
            articolo.approved_by = pub.approved_by
            articolo.approved_at = pub.approved_at
            articolo.admin_notes = pub.admin_notes
            articolo.save()
        else:
            # Crea nuovo articolo da pubbliredazionale con slug unico
            titolo = pub.titolo or f"Pubbliredazionale {pub.nome_azienda}"
            base_slug = slugify(titolo)
            slug = base_slug
            counter = 1

            # Trova uno slug unico
            while Articolo.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1

            Articolo.objects.create(
                titolo=titolo,
                slug=slug,
                contenuto=pub.contenuto or '',
                sommario=pub.sommario or '',
                categoria=pub.categoria,
                foto=pub.foto or '',
                approvato=(pub.status == 'published'),
                fonte=pub.sito_web,
                data_creazione=pub.created_at,
                data_pubblicazione=pub.published_at,
                is_pubbliredazionale=True,
                pubbliredazionale_user=pub.user,
                nome_azienda=pub.nome_azienda,
                sito_web=pub.sito_web,
                pubbliredazionale_status=pub.status,
                interview_data=pub.interview_data,
                payment_status=pub.payment_status,
                payment_method=pub.payment_method or '',
                payment_transaction_id=pub.payment_transaction_id or '',
                payment_date=pub.payment_date,
                total_price=pub.total_price,
                approved_by=pub.approved_by,
                approved_at=pub.approved_at,
                admin_notes=pub.admin_notes
            )


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_articolopubbliredazionale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Visibili solo agli admin', verbose_name='Note amministrative'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approvato il'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pubbliredazionali_approvati', to=settings.AUTH_USER_MODEL, verbose_name='Approvato da'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='interview_data',
            field=models.JSONField(blank=True, default=dict, help_text='Conversazione AI e informazioni raccolte', verbose_name='Dati intervista'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='is_pubbliredazionale',
            field=models.BooleanField(db_index=True, default=False, help_text='È un articolo pubbliredazionale'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='nome_azienda',
            field=models.CharField(blank=True, help_text="Nome dell'azienda per il pubbliredazionale", max_length=200, verbose_name='Nome azienda'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data pagamento'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Metodo di pagamento'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'In attesa'), ('completed', 'Completato'), ('failed', 'Fallito'), ('refunded', 'Rimborsato')], default='', max_length=20, verbose_name='Stato pagamento'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID transazione'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='pubbliredazionale_status',
            field=models.CharField(blank=True, choices=[('draft', 'Bozza'), ('interview_in_progress', 'Intervista in corso'), ('interview_completed', 'Intervista completata'), ('pending_payment', 'In attesa di pagamento'), ('pending_approval', 'In attesa di approvazione'), ('approved', 'Approvato'), ('published', 'Pubblicato'), ('rejected', 'Rifiutato')], help_text='Stato del workflow pubbliredazionale', max_length=30, verbose_name='Stato pubbliredazionale'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='pubbliredazionale_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pubbliredazionali', to=settings.AUTH_USER_MODEL, verbose_name='Utente richiedente'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='sito_web',
            field=models.URLField(blank=True, help_text="URL del sito web dell'azienda", max_length=500, verbose_name='Sito web azienda'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='Prezzo totale (€)'),
        ),
        migrations.RunPython(migrate_pubbliredazionali, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(
            name='ArticoloPubbliredazionale',
        ),
    ]
