# Generated by Django 5.2.7 on 2025-11-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_articolo_admin_notes_articolo_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='pubbliredazionale_status',
        ),
    ]
