# Generated by Django 5.2.7 on 2025-11-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_articolo_pubbliredazionale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'In attesa'), ('saved', 'Salvato (senza pagamento)'), ('completed', 'Completato'), ('failed', 'Fallito'), ('refunded', 'Rimborsato')], default='', max_length=20, verbose_name='Stato pagamento'),
        ),
    ]
