# Generated by Django 5.2.7 on 2025-11-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_add_saved_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='intervistato_cognome',
            field=models.CharField(blank=True, help_text='Cognome della persona intervistata', max_length=100, verbose_name='Cognome intervistato'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='intervistato_nome',
            field=models.CharField(blank=True, help_text='Nome della persona intervistata', max_length=100, verbose_name='Nome intervistato'),
        ),
    ]
