# Generated by Django 5.2.7 on 2025-11-13 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_add_promotional_codes'),
        ('home', '0030_add_intervistato_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Importo dello sconto applicato', max_digits=10, verbose_name='Sconto applicato (€)'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pubbliredazionale_uses', to='admin_panel.promotionalcode', verbose_name='Codice promozionale applicato'),
        ),
    ]
