# Generated by Django 5.2.7 on 2025-11-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_add_promo_code_to_articolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Prezzo totale (€)'),
        ),
    ]
