# Generated by Django 5.2.5 on 2025-11-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_merge_20251104_1349'),
        ('home', '0031_add_promo_code_to_articolo'),
    ]

    operations = [
    ]
