# Generated by Django 5.2.7 on 2025-11-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_change_pubbliredazionale_price_to_50'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='ai_model_used',
            field=models.CharField(blank=True, help_text="Modello AI utilizzato per generare l'articolo (es. claude-3-7-sonnet, gpt-4-turbo)", max_length=50, null=True),
        ),
    ]
