# Generated by Django 5.2.5 on 2025-11-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_change_pubbliredazionale_price_to_50'),
        ('home', '0032_merge_20251114_1145'),
    ]

    operations = [
    ]
