# Generated by Django 5.2.7 on 2025-11-22 19:13

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_add_promotional_codes'),
        ('home', '0033_articolo_ai_model_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolo',
            options={'verbose_name': 'Articolo', 'verbose_name_plural': 'Articoli'},
        ),
        migrations.AlterField(
            model_name='articolo',
            name='approvato',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='categoria',
            field=models.CharField(db_index=True, default='Generale', max_length=100),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='data_pubblicazione',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddIndex(
            model_name='articolo',
            index=models.Index(fields=['approvato', '-data_pubblicazione'], name='home_artico_approva_065acd_idx'),
        ),
        migrations.AddIndex(
            model_name='articolo',
            index=models.Index(fields=['categoria', 'approvato', '-data_pubblicazione'], name='home_artico_categor_86425b_idx'),
        ),
        migrations.AddIndex(
            model_name='articolo',
            index=models.Index(fields=['slug'], name='home_artico_slug_6d9fd0_idx'),
        ),
    ]
