# Generated by Django 5.2.5 on 2025-11-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_articolo_ai_model_used'),
        ('home', '0033_merge_20251115_1651'),
    ]

    operations = [
    ]
