# Generated by Django 5.2.7 on 2025-11-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_articolo_options_alter_articolo_approvato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='telegram_notified',
            field=models.BooleanField(db_index=True, default=False, help_text="Indica se l'articolo è stato notificato su Telegram"),
        ),
    ]
