# Generated by Django 5.2.5 on 2025-11-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_articolo_options_alter_articolo_approvato_and_more'),
        ('home', '0034_merge_20251120_1500'),
    ]

    operations = [
    ]
