# Generated by Django 5.2.5 on 2025-11-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_add_telegram_notified_field'),
        ('home', '0035_merge_20251122_2019'),
    ]

    operations = [
    ]
