# Generated by Django 5.2.7 on 2025-12-13 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_add_telegram_notified_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPublicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], db_index=True, max_length=20)),
                ('success', models.BooleanField(help_text='Pubblicazione riuscita')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, help_text='Messaggio di errore se fallita', null=True)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_publications', to='home.articolo')),
            ],
            options={
                'verbose_name': 'Log Pubblicazione Social',
                'verbose_name_plural': 'Log Pubblicazioni Social',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['articolo', 'platform', 'success'], name='home_social_articol_5c4376_idx')],
            },
        ),
    ]
