# Generated by Django 5.2.7 on 2025-12-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_socialpublicationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10, verbose_name='Prezzo totale (€)'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='spotlight',
            field=models.BooleanField(db_index=True, default=False, help_text='Articolo in evidenza nella sezione spotlight (max 4)'),
        ),
    ]
