# Generated by Django 5.2.5 on 2025-12-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_socialpublicationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10, verbose_name='Prezzo totale (€)'),
        ),
    ]
