# Generated by Django 5.2.7 on 2025-12-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_socialpublicationlog'),
        ('home', '0037_pubbliredazionale_price_and_spotlight'),
    ]

    operations = [
    ]
