# Generated by Django 5.2.7 on 2025-12-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_articolo_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='spotlight',
            field=models.BooleanField(db_index=True, default=False, help_text='Articolo in evidenza nella sezione spotlight (max 4)'),
        ),
    ]
