# Generated by Django 5.2.7 on 2025-12-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_merge_20251220_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='data_modifica',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text="Data ultima modifica dell'articolo"),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10, verbose_name='Prezzo totale (€)'),
        ),
    ]
