# Generated by Django 5.2.7 on 2025-12-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_articolo_data_modifica_alter_articolo_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10, verbose_name='Prezzo totale (€)'),
        ),
    ]
