# Generated by Django 5.2.5 on 2025-12-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_articolo_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
