# Generated by Django 5.2.7 on 2025-12-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_articolo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='articolo',
            name='approved_by',
        ),
    ]
