# Generated by Django 5.2.5 on 2025-12-20 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_merge_20251125_1304'),
        ('home', '0042_pubbliredazionale_price_and_spotlight'),
    ]

    operations = [
    ]
