# Generated by Django 5.2.7 on 2026-01-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_remove_pubbliredazionale_approval_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
