# Generated by Django 5.2.7 on 2026-01-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_articolo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
