# Generated by Django 5.2.5 on 2025-12-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_articolo_total_price'),
        ('home', '0043_merge_20251221_0023'),
    ]

    operations = [
    ]
