# Generated by Django 5.2.7 on 2026-01-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_articolo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='intervistato_ruolo',
            field=models.CharField(blank=True, help_text="Ruolo o carica dell'intervistato in azienda (es: Titolare, Direttore)", max_length=100, verbose_name='Ruolo in azienda'),
        ),
    ]
