# Generated by Django 5.2.5 on 2025-12-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_remove_pubbliredazionale_approval_fields'),
        ('home', '0044_merge_20251221_2200'),
    ]

    operations = [
    ]
