# Generated by Django 5.2.5 on 2026-01-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_articolo_slug'),
        ('home', '0045_merge_20251230_1201'),
    ]

    operations = [
    ]
