# Generated by Django 5.2.5 on 2026-02-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_add_intervistato_ruolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='categoria',
            field=models.CharField(choices=[('Attualità', 'Attualità'), ('Cronaca', 'Cronaca'), ('Cultura & Eventi', 'Cultura & Eventi'), ('Politica', 'Politica'), ('Sport', 'Sport'), ("L'Eco del Consiglio", "L'Eco del Consiglio"), ('Cosa fare oggi', 'Cosa fare oggi'), ('Editoriale', 'Editoriale')], db_index=True, default='Attualità', max_length=100),
        ),
    ]
