# Generated by Django 5.2.5 on 2026-01-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_add_intervistato_ruolo'),
        ('home', '0046_merge_20260104_1435'),
    ]

    operations = [
    ]
