# Generated by Django 5.2.5 on 2026-03-08 19:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_articolo_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_invio', models.DateTimeField(auto_now_add=True)),
                ('oggetto', models.CharField(max_length=200)),
                ('num_destinatari', models.IntegerField(default=0)),
                ('num_articoli', models.IntegerField(default=0)),
                ('stato', models.CharField(choices=[('success', 'Completato'), ('partial', 'Parziale'), ('failed', 'Fallito'), ('skipped', 'Saltato (nessun articolo)')], max_length=20)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Log Newsletter',
                'verbose_name_plural': 'Log Newsletter',
                'ordering': ['-data_invio'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('attivo', models.BooleanField(default=True)),
                ('data_iscrizione', models.DateTimeField(auto_now_add=True)),
                ('token_disiscrizione', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Iscritto Newsletter',
                'verbose_name_plural': 'Iscritti Newsletter',
                'ordering': ['-data_iscrizione'],
            },
        ),
        migrations.AddField(
            model_name='articolo',
            name='escludi_newsletter',
            field=models.BooleanField(default=False, help_text='Se selezionato, questo articolo non verrà incluso nella newsletter'),
        ),
    ]
