# Generated by Django 5.2.5 on 2026-02-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_articolo_categoria'),
        ('home', '0047_merge_20260126_1458'),
    ]

    operations = [
    ]
