# Generated by Django 5.2.5 on 2026-04-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_newsletterlog_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Tag separati da virgola. Es: "Carpi calcio, Serie D, Carpi FC"', max_length=200),
        ),
    ]
