# Generated by Django 5.2.5 on 2026-04-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_add_tags_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiusage',
            name='api_type',
            field=models.CharField(choices=[('anthropic', 'Anthropic Claude'), ('openai', 'OpenAI'), ('google_search', 'Google Search')], help_text='Tipo di API utilizzata', max_length=20),
        ),
    ]
