# Generated by Django 5.2.5 on 2026-03-08 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_newsletterlog_newslettersubscriber_and_more'),
        ('home', '0048_merge_20260221_0940'),
    ]

    operations = [
    ]
