# Generated by Django 5.2.5 on 2026-05-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_add_openai_apiusage_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='titolo_seo',
            field=models.CharField(blank=True, default='', help_text='Title tag SEO per Google (max 60 char, keyword-first). Se vuoto usa il titolo principale.', max_length=70),
        ),
    ]
