# Generated by Django 5.2.5 on 2026-04-29 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_add_tags_field'),
        ('home', '0049_merge_20260308_2145'),
    ]

    operations = [
    ]
