# Generated by Django 5.2.5 on 2026-04-29 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_add_openai_apiusage_choice'),
        ('home', '0050_merge_0048_add_tags_field_0049_merge_20260308_2145'),
    ]

    operations = [
    ]
