# Generated by Django 5.2.5 on 2026-05-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_add_titolo_seo'),
        ('home', '0051_merge_20260430_0019'),
    ]

    operations = [
    ]
