# Generated by Django 5.2.5 on 2026-05-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_add_facebook_reel_platform_choice'),
        ('home', '0052_merge_0050_add_titolo_seo_0051_merge_20260430_0019'),
    ]

    operations = [
    ]
