# Generated by Django 5.2.5 on 2026-05-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_add_facebook_story_platform_choice'),
        ('home', '0053_merge_20260516_2108'),
    ]

    operations = [
    ]
