# Generated by Django 5.2.5 on 2026-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_socialpublicationlog_ig_media_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='autore',
            field=models.CharField(default='Sven Rinaldi', help_text="Autore dell'articolo (firma redazionale o personale)", max_length=120),
        ),
    ]
