# Generated by Django 5.2.5 on 2026-05-16 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_add_instagram_story_reel_platform_choices'),
        ('home', '0054_merge_20260517_0056'),
    ]

    operations = [
    ]
