# Generated by Django 5.2.5 on 2026-05-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_social_link_tracking'),
        ('home', '0055_merge_20260517_0146'),
    ]

    operations = [
    ]
