# Generated by Django 5.2.5 on 2026-05-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_articolo_autore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticoloRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(max_length=100, unique=True)),
                ('new_slug', models.SlugField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(default='slug-malformato', help_text='Motivo del rename', max_length=120)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='home.articolo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
