# Generated by Django 5.2.5 on 2026-05-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_socialpublicationlog_ig_media_history'),
        ('home', '0056_merge_20260518_1121'),
    ]

    operations = [
    ]
