# Generated by Django 5.2.5 on 2026-05-24 20:30

from django.db import migrations, models


def assign_redazione_to_all(apps, schema_editor):
    """
    Ribattezza TUTTI gli articoli a 'Redazione Ombra del Portico'.
    La categoria 'Editoriale' e' un vecchio test inattivo, non serve
    distinguere.
    """
    Articolo = apps.get_model('home', 'Articolo')
    Articolo.objects.all().update(autore='Redazione Ombra del Portico')


def reverse(apps, schema_editor):
    Articolo = apps.get_model('home', 'Articolo')
    Articolo.objects.filter(
        autore='Redazione Ombra del Portico'
    ).update(autore='Sven Rinaldi')


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_articoloredirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='autore',
            field=models.CharField(db_index=True, default='Redazione Ombra del Portico', help_text="Autore dell'articolo. Default 'Redazione Ombra del Portico'. Usa nome persona reale per editoriali firmati o pubbliredazionali con firma dell'autore.", max_length=120),
        ),
        migrations.RunPython(assign_redazione_to_all, reverse),
    ]
