# Generated by Django 5.2.5 on 2026-05-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_articoloredirect'),
        ('home', '0057_merge_20260519_2051'),
    ]

    operations = [
    ]
