# Generated by Django 5.2.5 on 2026-05-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_alter_articolo_autore'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='image_16x9',
            field=models.ImageField(blank=True, help_text='Versione WebP 1200x675 per social e NewsArticle', null=True, upload_to='images/articles/'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='image_1x1',
            field=models.ImageField(blank=True, help_text='Versione WebP 1200x1200 per NewsArticle', null=True, upload_to='images/articles/'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='image_4x3',
            field=models.ImageField(blank=True, help_text='Versione WebP 1200x900 per NewsArticle', null=True, upload_to='images/articles/'),
        ),
    ]
