# Generated by Django 5.2.5 on 2026-05-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_alter_articolo_autore'),
        ('home', '0058_merge_0056_articoloredirect_0057_merge_20260519_2051'),
    ]

    operations = [
    ]
