# Generated by Django 5.2.5 on 2026-05-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_add_article_image_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='image_16x9',
            field=models.ImageField(blank=True, help_text='Versione WebP 1200x675 per social e NewsArticle', max_length=180, null=True, upload_to='images/articles/'),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='image_1x1',
            field=models.ImageField(blank=True, help_text='Versione WebP 1200x1200 per NewsArticle', max_length=180, null=True, upload_to='images/articles/'),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='image_4x3',
            field=models.ImageField(blank=True, help_text='Versione WebP 1200x900 per NewsArticle', max_length=180, null=True, upload_to='images/articles/'),
        ),
    ]
