# Generated by Django 5.2.5 on 2026-05-25 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_add_article_image_variants'),
        ('home', '0059_merge_20260524_2246'),
    ]

    operations = [
    ]
