# Generated by Django 5.2.5 on 2026-05-25 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_extend_article_image_field_lengths'),
        ('home', '0060_merge_20260526_0107'),
    ]

    operations = [
    ]
