# Generated by Django 5.2.5 on 2026-06-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_articolo_foto_valida'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articolo',
            index=models.Index(fields=['is_pubbliredazionale', 'approvato', 'payment_status'], name='idx_articolo_publi_pub'),
        ),
        migrations.AddIndex(
            model_name='articolo',
            index=models.Index(condition=models.Q(('spotlight', True)), fields=['spotlight', '-data_pubblicazione'], name='idx_articolo_spotlight'),
        ),
        migrations.AddIndex(
            model_name='socialpublicationlog',
            index=models.Index(fields=['platform', 'success', 'published_at'], name='idx_socialpub_published'),
        ),
    ]
