# Generated by Django 5.2.5 on 2026-06-09 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_articolo_idx_articolo_publi_pub_and_more'),
        ('home', '0061_merge_20260526_0121'),
    ]

    operations = [
    ]
