# Generated by Django 5.2.5 on 2026-07-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_merge_20260610_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiusage',
            name='api_type',
            field=models.CharField(choices=[('anthropic', 'Anthropic Claude'), ('openai', 'OpenAI'), ('openrouter', 'OpenRouter'), ('google_search', 'Google Search')], help_text='Tipo di API utilizzata', max_length=20),
        ),
    ]
