# Generated by Django 5.2.5 on 2026-07-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_alter_apiusage_api_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='tfidf_terms',
            field=models.JSONField(blank=True, help_text='Vettore TF-IDF (termine->peso) per il gate di rilevanza del linking interno', null=True),
        ),
    ]
