# Generated by Django 5.2.5 on 2026-07-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_articolo_tfidf_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='spunto_social',
            field=models.CharField(blank=True, default='', help_text="Domanda finale per il post Facebook (genera commenti). Generata dall'AI, modificabile prima dell'approvazione. Se vuota, il post resta come prima.", max_length=280),
        ),
    ]
