# Generated by Django 5.2.5 on 2026-07-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_articolo_spunto_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='autore',
        ),
    ]
