# Generated by Django 5.2.5 on 2026-09-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_remove_articolo_autore'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='da_rielaborare',
            field=models.BooleanField(db_index=True, default=False, help_text="Notizia grezza di un monitor con generazione AI spenta: va rielaborata con l'AI prima di poterla approvare", verbose_name='Da rielaborare'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='monitor_origine',
            field=models.ForeignKey(blank=True, help_text="Monitor che ha prodotto l'articolo: le sue regole AI si usano per la rielaborazione", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articoli', to='home.monitorconfig'),
        ),
    ]
