# Generated by Django 5.2.7 on 2025-11-04 18:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nome identificativo del banner', max_length=200, verbose_name='Titolo')),
                ('image', models.ImageField(help_text='Formato consigliato: 728x90 o 300x250', upload_to='banners/', verbose_name='Immagine')),
                ('link_url', models.URLField(help_text='Dove viene reindirizzato chi clicca sul banner', verbose_name='URL di destinazione')),
                ('alt_text', models.CharField(help_text='Descrizione per accessibilità', max_length=200, verbose_name='Testo alternativo')),
                ('position', models.CharField(choices=[('header', 'Header (Sopra il titolo)'), ('sidebar_top', 'Sidebar Alto'), ('sidebar_middle', 'Sidebar Centro'), ('sidebar_bottom', 'Sidebar Basso'), ('between_articles', 'Tra gli articoli (Homepage)'), ('article_top', 'Inizio articolo'), ('article_middle', 'Centro articolo'), ('article_bottom', 'Fine articolo'), ('footer', 'Footer')], max_length=50, verbose_name='Posizione')),
                ('priority', models.IntegerField(default=1, help_text='Priorità di visualizzazione (1=bassa, 10=alta)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Priorità')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data inizio')),
                ('end_date', models.DateTimeField(verbose_name='Data fine')),
                ('duration_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durata (giorni)')),
                ('price_per_day', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Prezzo al giorno (€)')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prezzo totale (€)')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('pending_payment', 'In attesa di pagamento'), ('active', 'Attivo'), ('paused', 'In pausa'), ('expired', 'Scaduto'), ('rejected', 'Rifiutato')], default='draft', max_length=20, verbose_name='Stato')),
                ('payment_status', models.CharField(choices=[('pending', 'In attesa'), ('completed', 'Completato'), ('failed', 'Fallito'), ('refunded', 'Rimborsato')], default='pending', max_length=20, verbose_name='Stato pagamento')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Metodo di pagamento')),
                ('payment_transaction_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID transazione')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data pagamento')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Visualizzazioni')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Click')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('admin_notes', models.TextField(blank=True, help_text='Visibili solo agli admin', verbose_name='Note amministrative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
                'ordering': ['-created_at'],
            },
        ),
    ]
