# Generated by Django 5.2.7 on 2025-11-08 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='approved',
            field=models.BooleanField(default=False, help_text='Il banner deve essere approvato da un amministratore prima di poter essere attivato', verbose_name='Approvato'),
        ),
        migrations.AddField(
            model_name='banner',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approvato il'),
        ),
        migrations.AddField(
            model_name='banner',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_banners', to=settings.AUTH_USER_MODEL, verbose_name='Approvato da'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='status',
            field=models.CharField(choices=[('draft', 'Bozza'), ('pending_approval', 'In attesa di approvazione'), ('pending_payment', 'In attesa di pagamento'), ('active', 'Attivo'), ('paused', 'In pausa'), ('expired', 'Scaduto'), ('rejected', 'Rifiutato')], default='draft', max_length=20, verbose_name='Stato'),
        ),
    ]
