# Generated by Django 5.2.7 on 2025-11-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_banner_approved_banner_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Immagine del banner (sarà convertita automaticamente in WebP)', upload_to='banners/', verbose_name='Immagine'),
        ),
    ]
