# Generated by Django 5.2.7 on 2025-11-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'In attesa'), ('saved', 'Salvato (senza pagamento)'), ('completed', 'Completato'), ('failed', 'Fallito'), ('refunded', 'Rimborsato')], default='pending', max_length=20, verbose_name='Stato pagamento'),
        ),
    ]
