# Generated by Django 5.2.7 on 2025-11-13 12:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_add_saved_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Importo dello sconto applicato', max_digits=10, verbose_name='Sconto applicato (€)'),
        ),
        migrations.CreateModel(
            name='PromotionalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codice univoco (es: ESTATE2024, PROMO50)', max_length=50, unique=True, verbose_name='Codice')),
                ('description', models.CharField(help_text='Descrizione interna del codice', max_length=200, verbose_name='Descrizione')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentuale (%)'), ('fixed', 'Importo fisso (€)'), ('free_banner', 'Banner gratuito'), ('free_pubbliredazionale', 'Pubbliredazionale gratuito')], default='percentage', max_length=30, verbose_name='Tipo sconto')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Percentuale (0-100) o importo fisso in €', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valore sconto')),
                ('applies_to', models.CharField(choices=[('banner', 'Solo Banner'), ('pubbliredazionale', 'Solo Pubbliredazionali'), ('both', 'Entrambi')], default='both', max_length=20, verbose_name='Si applica a')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valido da')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Lascia vuoto per nessuna scadenza', null=True, verbose_name='Valido fino a')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Numero massimo di volte che può essere usato (lascia vuoto per illimitato)', null=True, verbose_name='Utilizzi massimi')),
                ('current_uses', models.PositiveIntegerField(default=0, editable=False, verbose_name='Utilizzi correnti')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='Importo minimo per applicare lo sconto (0 = nessun minimo)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importo minimo')),
                ('is_active', models.BooleanField(default=True, help_text='Il codice può essere utilizzato', verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
            ],
            options={
                'verbose_name': 'Codice Promozionale',
                'verbose_name_plural': 'Codici Promozionali',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_uses', to='admin_panel.promotionalcode', verbose_name='Codice promozionale applicato'),
        ),
    ]
