# Generated by Django 5.2.7 on 2025-12-20 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_add_promotional_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='priority',
            field=models.IntegerField(default=3, help_text='Priorità di visualizzazione (1=massima, 5=minima)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Priorità'),
        ),
    ]
