# Generated by Django 5.2.7 on 2025-12-21 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_banner_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=1.7, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Prezzo al giorno (€)'),
        ),
    ]
