# Generated by Django 5.2.5 on 2026-03-09 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_banner_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_vertical',
            field=models.ImageField(blank=True, help_text='Card verticale — tra gli articoli in homepage (sarà convertita in WebP)', null=True, upload_to='banners/', verbose_name='Banner verticale (300×250)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Leaderboard orizzontale — header su tutte le pagine (sarà convertita in WebP)', null=True, upload_to='banners/', verbose_name='Banner orizzontale (728×90)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=1.7, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prezzo al giorno (€)'),
        ),
    ]
