# Generated by Django 5.2.5 on 2026-04-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_banner_campaign_two_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Leaderboard orizzontale — header su tutte le pagine (sarà convertita in WebP)', null=True, upload_to='banners/', verbose_name='Banner orizzontale (728×270)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_vertical',
            field=models.ImageField(blank=True, help_text='Card verticale — tra gli articoli in homepage (sarà convertita in WebP)', null=True, upload_to='banners/', verbose_name='Banner verticale (300×600)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('both', 'Campagna completa (orizzontale + verticale) — header + tra gli articoli'), ('header', 'Solo orizzontale (728×270) — header su tutte le pagine'), ('between_articles', 'Solo verticale (300×600) — tra gli articoli in homepage')], max_length=50, verbose_name='Posizione'),
        ),
    ]
